site_name: Apunts de matemàtiques per Batxillerat
theme:
  name: material
  language: ca
  palette:
    primary: indigo
    accent: light blue
  features:
    - navigation.tabs      # Menú superior per a les grans seccions
    - navigation.sections  # Menú lateral organitzat

markdown_extensions:
  - pymdownx.arithmatex:   # L'extensió per a matemàtiques
      generic: true
  - admonition             # Per crear "notes" o "avisos" destacats
  - pymdownx.details       # Per fer desplegables (ex: solucions d'exercicis)
  - attr_list              # Per poder enquadrar
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Geometria Analítica:
      - "Vectors al pla": geometria/vectors.md
      - "Sistema de referència i punts al pla": geometria/geometria_pla.md
      
